import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  try {
    const { idea, mode = "both", language = "AUTO" } = await req.json();
    if (!idea || typeof idea !== "string" || !idea.trim()) {
      return new Response(JSON.stringify({ error: "Missing 'idea'" }), {
        status: 400,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY");
    if (!LOVABLE_API_KEY) throw new Error("LOVABLE_API_KEY not configured");

    const focus =
      mode === "views"
        ? "Bias outputs toward maximum TikTok reach, retention, and viral loops."
        : mode === "money"
        ? "Bias outputs toward subscription revenue, conversion, and SaaS value."
        : "Balance TikTok virality and subscription monetization equally.";

    const languageRule =
      language && language !== "AUTO"
        ? `Respond ONLY in this language code: ${language}. No mixing languages.`
        : `Detect the language of the user's idea automatically (Hebrew, English, Spanish, Arabic, French, etc.) and respond ONLY in that language across ALL fields. No mixing. Adapt tone and cultural style.`;

    const systemPrompt = `You are an elite AI system combining: TikTok Viral Growth Engineer, SaaS Monetization Architect, Subscription Conversion Expert, Behavioral Psychology & Habit Engine, and Creator Growth System.

🌍 LANGUAGE: ${languageRule}

🎯 GOAL: Turn ANY idea into (1) viral TikTok content strategy, (2) monetization plan, (3) subscription SaaS value, (4) daily creator growth loop.

${focus}

📱 TIKTOK VIRAL ENGINE — must include scroll-stopping 3s hook, retention structure, comment bait, daily TikTok idea, viral loop tip.
💰 SAAS + SUBSCRIPTION ENGINE — must include monetization model (freemium/subscription/toolkit/automation), psychological reason people pay, premium-only feature, monthly price suggestion.
🔁 DAILY GROWTH LOOP — daily challenge, streak motivation, next-level improvement.
🚀 GROWTH LOOP SYSTEM — viral distribution plan, user return hook, content series system (5–10 videos).

📈 TIKTOK USER ACQUISITION ENGINE — every output must also generate VIRAL USER ACQUISITION for the tool itself. Generate organic TikTok content that attracts NEW USERS to the app. NEVER feels like an ad. Must create the loop: viewer sees video → wants same result → opens tool → generates content → posts again. Soft conversion only: position the tool as a "secret weapon creators use", outputs as "cheat codes for TikTok", trigger curiosity gap ("this was generated by an AI tool"). Must create an "I need this app" effect.

⚠️ RULES:
- No fluff, no long explanations.
- Works for ANY niche.
- Optimized for TikTok virality.
- Includes SaaS + subscription thinking.
- Creates daily return behavior.
- Feels like a real $20/month product.
- All scores are integers 1–10.
- Video script: 3–5 steps, each with visual + spoken line.
- Hashtags: exactly 5 global hashtags (with #).
- Caption: short, natural, engaging.

You MUST call the viral_strategy function with all required fields.`;

    const response = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${LOVABLE_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "google/gemini-3-flash-preview",
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user", content: `Idea / product: ${idea}\n\nGenerate the full elite TikTok + SaaS viral growth strategy.` },
        ],
        tools: [
          {
            type: "function",
            function: {
              name: "viral_strategy",
              description: "Return an elite TikTok + SaaS viral growth strategy.",
              parameters: {
                type: "object",
                properties: {
                  viralityScore: { type: "integer", minimum: 1, maximum: 10 },
                  viralityReason: { type: "string" },
                  moneyScore: { type: "integer", minimum: 1, maximum: 10 },
                  moneyReason: { type: "string" },
                  subscriptionScore: { type: "integer", minimum: 1, maximum: 10 },
                  subscriptionReason: { type: "string" },
                  executionScore: { type: "integer", minimum: 1, maximum: 10 },
                  executionReason: { type: "string" },

                  hook: { type: "string", description: "TikTok viral hook — first 3s, scroll-stopping." },
                  scriptSteps: {
                    type: "array",
                    minItems: 3,
                    maxItems: 5,
                    items: {
                      type: "object",
                      properties: {
                        visual: { type: "string" },
                        spoken: { type: "string" },
                      },
                      required: ["visual", "spoken"],
                      additionalProperties: false,
                    },
                  },

                  retentionStructure: { type: "string", description: "How to keep viewers watching till the end." },
                  commentBait: { type: "string", description: "One line that triggers comments." },
                  viralLoopTip: { type: "string", description: "How this video becomes a self-feeding series." },
                  distributionPlan: { type: "string", description: "How this idea spreads on TikTok organically." },

                  monetizationModel: {
                    type: "string",
                    enum: ["freemium", "subscription", "creator toolkit", "automation tool"],
                  },
                  monetizationPlan: { type: "string", description: "Concrete monetization explanation." },
                  whyPeoplePay: { type: "string", description: "Psychological reason: save time / make money / go viral / avoid effort." },
                  premiumFeature: { type: "string", description: "One feature only paid users get." },
                  pricingSuggestion: { type: "string", description: "Simple monthly price suggestion, e.g. $9/mo." },

                  dailyIdea: { type: "string", description: "Ready-to-post TikTok idea for tomorrow." },
                  dailyChallenge: { type: "string", description: "One small action user must do today." },
                  streakMotivation: { type: "string", description: "Short motivational sentence to keep users returning." },
                  improvementTip: { type: "string", description: "One tip to improve results tomorrow." },
                  returnHook: { type: "string", description: "Why the user comes back tomorrow." },
                  seriesSystem: { type: "string", description: "How to turn this into 5–10 videos automatically." },

                  caption: { type: "string" },
                  hashtags: {
                    type: "array",
                    minItems: 5,
                    maxItems: 5,
                    items: { type: "string" },
                  },
                },
                required: [
                  "viralityScore", "viralityReason",
                  "moneyScore", "moneyReason",
                  "subscriptionScore", "subscriptionReason",
                  "executionScore", "executionReason",
                  "hook", "scriptSteps",
                  "retentionStructure", "commentBait", "viralLoopTip", "distributionPlan",
                  "monetizationModel", "monetizationPlan", "whyPeoplePay", "premiumFeature", "pricingSuggestion",
                  "dailyIdea", "dailyChallenge", "streakMotivation", "improvementTip", "returnHook", "seriesSystem",
                  "caption", "hashtags",
                ],
                additionalProperties: false,
              },
            },
          },
        ],
        tool_choice: { type: "function", function: { name: "viral_strategy" } },
      }),
    });

    if (!response.ok) {
      if (response.status === 429) {
        return new Response(JSON.stringify({ error: "Rate limit exceeded. Try again shortly." }), {
          status: 429,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        });
      }
      if (response.status === 402) {
        return new Response(JSON.stringify({ error: "AI credits exhausted. Add funds to continue." }), {
          status: 402,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        });
      }
      const t = await response.text();
      console.error("Gateway error", response.status, t);
      return new Response(JSON.stringify({ error: "AI gateway error" }), {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const data = await response.json();
    const toolCall = data.choices?.[0]?.message?.tool_calls?.[0];
    if (!toolCall) throw new Error("No structured output returned");
    const args = JSON.parse(toolCall.function.arguments);

    return new Response(JSON.stringify(args), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (e) {
    console.error("generate-strategy error:", e);
    return new Response(JSON.stringify({ error: e instanceof Error ? e.message : "Unknown error" }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
